import { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, RefreshCw } from 'lucide-react';
import ResultsDashboard from '../components/results/ResultsDashboard';
import LoadingSpinner from '../components/shared/LoadingSpinner';
import SignalBadge from '../components/shared/SignalBadge';
import type { AnalysisResultResponse } from '../types/api';

const API_BASE = '/api';

export default function CompetitionAnalysis() {
  const { analysisId } = useParams<{ analysisId: string }>();
  const navigate = useNavigate();
  const [data, setData] = useState<AnalysisResultResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [fetchKey, setFetchKey] = useState(0);

  useEffect(() => {
    if (!analysisId) {
      console.warn('[CompetitionAnalysis] No analysis ID provided');
      setLoading(false);
      setError('No analysis ID provided.');
      return;
    }
    let cancelled = false;
    setLoading(true);
    setError(null);
    console.info(`[CompetitionAnalysis] Loading analysis: ${analysisId}`);

    (async () => {
      try {
        const startTime = Date.now();

        // Try to load by the provided ID/ticker
        let res = await fetch(`${API_BASE}/competition/analysis/${analysisId}`, {
          signal: AbortSignal.timeout(30000),
        });
        const duration = Date.now() - startTime;

        let body = await res.json().catch(() => ({}));

        // If not found and looks like a ticker, try uppercasing it
        if (!res.ok && analysisId && !analysisId.includes('-')) {
          console.info(`[CompetitionAnalysis] Not found, trying uppercase ticker`);
          res = await fetch(`${API_BASE}/competition/analysis/${analysisId.toUpperCase()}`, {
            signal: AbortSignal.timeout(30000),
          });
          body = await res.json().catch(() => ({}));
        }

        if (!res.ok) {
          const errMsg = body.error || `HTTP ${res.status}: Analysis not found. Make sure the LLM pipeline has completed for this instrument.`;
          console.error(`[CompetitionAnalysis] Failed to load analysis: ${errMsg}`);
          throw new Error(errMsg);
        }

        if (!cancelled) {
          console.info(`[CompetitionAnalysis] ✓ Loaded in ${duration}ms`);
          setData(body);
        }
      } catch (e: any) {
        const errMsg = e.message ?? String(e);
        if (!cancelled) {
          console.error(`[CompetitionAnalysis] Error: ${errMsg}`);
          setError(errMsg);
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();

    return () => {
      cancelled = true;
      console.debug(`[CompetitionAnalysis] Cleanup for ${analysisId}`);
    };
  }, [analysisId, fetchKey]);

  const handleRefresh = () => setFetchKey(k => k + 1);

  return (
    <div className="max-w-5xl mx-auto space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between">
        <button
          onClick={() => navigate('/competition')}
          className="flex items-center gap-2 text-sm text-trading-textdim hover:text-trading-text transition-colors cursor-pointer"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Competition Dashboard
        </button>
        {data && (
          <button
            onClick={handleRefresh}
            className="flex items-center gap-1.5 text-xs text-trading-textdim hover:text-trading-text transition-colors cursor-pointer"
          >
            <RefreshCw className="w-3.5 h-3.5" />
            Refresh
          </button>
        )}
      </div>

      {/* Source banner */}
      {data && (
        <div className="bg-trading-surface border border-trading-border rounded-xl p-4">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <div>
              <div className="flex items-center gap-3 mb-1">
                <h1 className="text-lg font-bold text-trading-text">
                  {(data as any).instrument_name || data.ticker}
                </h1>
                <span className="font-mono text-sm text-trading-textdim">{data.ticker}</span>
                <SignalBadge signal={data.signal} size="sm" />
              </div>
              <p className="text-xs text-trading-textdim">
                Competition signal · Analysis date: {data.analysis_date}
              </p>
            </div>
            <div className="text-right text-xs text-trading-textdim">
              <p>Generated by TradingAgents multi-agent pipeline</p>
              <p className="mt-0.5">
                Analysts:{' '}
                <span className="text-trading-text">
                  {((data as any).analysts_used as string[] | undefined)
                    ?.filter(a => ['Market Analyst','Sentiment Analyst','News Analyst','Fundamentals Analyst'].includes(a))
                    .map(a => a.replace(' Analyst', ''))
                    .join(', ') || 'Market, Fundamentals'}
                </span>
              </p>
              <p className="mt-0.5">
                Research team:{' '}
                <span className="text-trading-text">Bull, Bear, Research Manager, Trader, Risk Analysts, Portfolio Manager</span>
              </p>
            </div>
          </div>
        </div>
      )}

      {/* Content */}
      {loading && <LoadingSpinner label="Loading analysis…" />}

      {error && (
        <div className="bg-trading-red/10 border border-trading-red/30 rounded-xl p-4 text-sm text-trading-red">
          {error}
          {error.includes('LLM pipeline') && (
            <p className="mt-2 text-trading-textdim text-xs">
              Start the engine with LLM mode (without <code>--no-llm</code>) and wait for the first pipeline to complete.
            </p>
          )}
        </div>
      )}

      {data && !loading && (
        <ResultsDashboard result={data} />
      )}
    </div>
  );
}
